// Import the Student model.
const Student = require("../models/studentModel");

// Create an object to contain our controller functions.
const studentController = {

    // Controller function to get all students.
    getAllStudents: (req, res) => {
        // Ask the model to get all students.
        Student.getAllStudents((error, results) => {
            // Check if there was a database error.
            if (error) {
                // Return HTTP status 500 and an error message.
                return res.status(500).json({
                    message: "Database error"
                });
            }

            // Return HTTP status 200.
            // Send all students as JSON.
            res.status(200).json(results);
        });
    },

    // Controller function to get one student.
    getStudentById: (req, res) => {
        // Get the ID from the URL.
        // Example: /api/students/5
        // req.params.id will contain 5.
        const id = req.params.id;

        // Ask the model to find the student.
        Student.getStudentById(id, (error, results) => {
            // Check for database errors.
            if (error) {
                // Send status code 500.
                return res.status(500).json({
                    message: "Database error"
                });
            }

            // Check if no student was found.
            if (results.length === 0) {
                // Send HTTP status 404.
                return res.status(404).json({
                    message: "Student not found"
                });
            }

            // Return the first student found.
            res.status(200).json(results[0]);
        });
    },

    // Controller function used to create a student.
    createStudent: (req, res) => {
        // Get the name from the JSON request body.
        const name = req.body.name;

        // Get the email from the JSON request body.
        const email = req.body.email;

        // Simple validation for beginners.
        if (!name || !email) {
            // Return status 400 if required values are missing.
            return res.status(400).json({
                message: "Name and email are required"
            });
        }

        // Create a JavaScript object.
        const student = {
            // Store the name.
            name: name,

            // Store the email.
            email: email
        };

        // Ask the model to save the student.
        Student.createStudent(student, (error, result) => {
            // Check if a database error happened.
            if (error) {
                // Send status code 500.
                return res.status(500).json({
                    message: "Database error"
                });
            }

            // Send status code 201.
            res.status(201).json({
                // Send a success message.
                message: "Student created successfully",

                // Send the ID generated by MySQL.
                id: result.insertId
            });
        });
    },

    // Controller function used to update a student.
    updateStudent: (req, res) => {
        // Get the student ID from the URL.
        const id = req.params.id;

        // Get the name from the request body.
        const name = req.body.name;

        // Get the email from the request body.
        const email = req.body.email;

        // Check that both values were provided.
        if (!name || !email) {
            // Return status 400 for a bad request.
            return res.status(400).json({
                message: "Name and email are required"
            });
        }

        // Create a student object.
        const student = {
            // Store the new name.
            name: name,

            // Store the new email.
            email: email
        };

        // Ask the model to update the student.
        Student.updateStudent(id, student, (error, result) => {
            // Check for database errors.
            if (error) {
                // Send HTTP status 500.
                return res.status(500).json({
                    message: "Database error"
                });
            }

            // Check whether a student was updated.
            if (result.affectedRows === 0) {
                // Send status code 404.
                return res.status(404).json({
                    message: "Student not found"
                });
            }

            // Return a successful response.
            res.status(200).json({
                message: "Student updated successfully"
            });
        });
    },

    // Controller function used to delete a student.
    deleteStudent: (req, res) => {
        // Get the student ID from the URL.
        const id = req.params.id;

        // Ask the model to delete the student.
        Student.deleteStudent(id, (error, result) => {
            // Check for database errors.
            if (error) {
                // Return status code 500.
                return res.status(500).json({
                    message: "Database error"
                });
            }

            // Check if no record was deleted.
            if (result.affectedRows === 0) {
                // Return status code 404.
                return res.status(404).json({
                    message: "Student not found"
                });
            }

            // Return status code 200.
            res.status(200).json({
                message: "Student deleted successfully"
            });
        });
    }
};

// Export the controller.
// The routes file will use it.
module.exports = studentController;
